#include "Headers/FileTypes.h"

std::map<std::string, std::string> fileTypes = {
	//Text formats
	{"txt", "Texts"},
	{"csv", "Texts"},
	{"xml", "Texts"},
	{"json", "Texts"},
	{"md", "Texts"},
	//Document formats
	{"doc", "Documents"},
	{"docx", "Documents"},
	{"xls", "Documents"},
	{"xlsx", "Documents"},
	{"ppt", "Documents"},
	{"pptx", "Documents"},
	{"odt", "Documents"},
	{"ods", "Documents"},
	{"odp", "Documents"},
	{"odg", "Documents"},
	{"odf", "Documents"},
	{"ods", "Documents"},
	{"odp", "Documents"},
	{"rtf", "Documents"},
	{"tex", "Documents"},
	{"wpd", "Documents"},
	{"wks", "Documents"},
	{"wps", "Documents"},
	{"wpd", "Documents"},
	{"pdf", "Documents"},
	{"log", "Documents"},
	{"epub", "Documents"},
	{"tex", "Documents"},
	//Picture formats
	{"jpg", "Pictures"},
	{"png", "Pictures"},
	{"gif", "Pictures"},
	{"bmp", "Pictures"},
	{"jpeg", "Pictures"},
	{"svg", "Pictures"},
	{"psd", "Pictures"},
	{"ico", "Pictures"},
	{"tif", "Pictures"},
	{"tiff", "Pictures"},
	//Audio formats
	{"m4a", "Music"},
	{"aiff", "Music"},
	{"ogg", "Music"},
	{"aac", "Music"},
	{"flac", "Music"},
	{"mp3", "Music"},
	{"wav", "Music"},
	//Video formats
	{"mp4", "Video"},
	{"mkv", "Video"},
	{"mov", "Video"},
	{"wmv", "Video"},
	{"flv", "Video"},
	{"3gp", "Video"},
	{"mpeg", "Video"},
	{"mpg", "Video"},
	{"m4v", "Video"},
	{"h264", "Video"},
	{"avi", "Video"},
	//Compressed formats
	{"zipx", "Compressed"},
	{"zip", "Compressed"},
	{"7z", "Compressed"},
	{"tar", "Compressed"},
	{"gz", "Compressed"},
	{"rar5", "Compressed"},
	{"rar", "Compressed"},
	/*//Cpp formats
	{"cpp", "C/C++"},
	{"c", "C/C++"},
	{"cc", "C/C++"},
	{"hpp", "C/C++"},
	{"h", "C/C++"},
	//Java formats
	{"java", "Java"},
	//Python formats
	{"py", "Python"},
	//Ruby formats
	{"rb", "Ruby"},
	//Perl formats
	{"pl", "Perl"},
	//Php formats
	{"php", "PHP"},
	//Javascript formats
	{"js", "Javascript"},
	//Html formats
	{"html", "HTML"},
	{"htm", "HTML"},
	//Css formats
	{"css", "CSS"},
	//Sql formats
	{"sql", "SQL"},
	//Shell formats
	{"sh", "Shell"},
	//Batch formats
	{"bat", "Batch"},
	//C# formats
	{"cs", "C#"},
	//Swift formats
	{"swift", "Swift"}*/
};